#!/usr/bin/env bash
# ─── _generate-override.sh ───────────────────────────────────
# Internal helper: regenerates docker-compose.override.yml from tenants.conf.
# Sourced by provision-tenant.sh and remove-tenant.sh.

_ROOT_DIR="${ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
_TENANTS_FILE="${TENANTS_FILE:-$_ROOT_DIR/tenants.conf}"
_OVERRIDE_FILE="${OVERRIDE_FILE:-$_ROOT_DIR/docker-compose.override.yml}"

# Start the override file
cat > "$_OVERRIDE_FILE" <<'HEADER'
# Auto-generated by MTP provisioning scripts.
# DO NOT EDIT — changes will be overwritten.
# Modify tenants via provision-tenant.sh / remove-tenant.sh

HEADER

# Read tenants.conf and generate a service block for each
if [[ -f "$_TENANTS_FILE" ]] && [[ -s "$_TENANTS_FILE" ]]; then
  echo "services:" >> "$_OVERRIDE_FILE"
  while IFS=' ' read -r name port; do
    # Skip empty lines and comments
    [[ -z "$name" || "$name" == \#* ]] && continue

    # Convert tenant name to env prefix: "client-a" → "CLIENT_A"
    env_prefix=$(echo "$name" | tr '[:lower:]-' '[:upper:]_')

    cat >> "$_OVERRIDE_FILE" <<EOF

  ${name}:
    image: \${OPENCLAW_IMAGE:-ghcr.io/openclaw/openclaw:main}
    container_name: mtp-${name}
    init: true
    restart: unless-stopped
    networks:
      - mtp
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
    environment:
      HOME: /home/node
      TERM: xterm-256color
      NODE_ENV: production
      OPENCLAW_GATEWAY_TOKEN: \${${env_prefix}_GATEWAY_TOKEN:?${env_prefix}_GATEWAY_TOKEN is required}
      TELEGRAM_BOT_TOKEN: \${${env_prefix}_TELEGRAM_TOKEN:?${env_prefix}_TELEGRAM_TOKEN is required}
      ANTHROPIC_API_KEY: \${${env_prefix}_ANTHROPIC_KEY:-}
      OPENAI_API_KEY: \${${env_prefix}_OPENAI_KEY:-}
      OPENROUTER_API_KEY: \${${env_prefix}_OPENROUTER_KEY:-}
    volumes:
      - ./data/${name}/.openclaw:/home/node/.openclaw
      - ./data/${name}/workspace:/home/node/.openclaw/workspace
    ports:
      - "\${${env_prefix}_PORT:-${port}}:18789"
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "lan",
        "--port",
        "18789",
      ]
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://127.0.0.1:18789/').then(r=>process.exit(r.ok||r.status===404?0:1)).catch(()=>process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
EOF
  done < "$_TENANTS_FILE"
else
  # No tenants — write an empty services block so the file is valid YAML
  echo "services: {}" >> "$_OVERRIDE_FILE"
fi

# Add network reference (must match base compose)
cat >> "$_OVERRIDE_FILE" <<'FOOTER'

networks:
  mtp:
    driver: bridge
FOOTER
